version: "0.1"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rome-deposit-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      # Add hot reloading support
      - ./.next:/app/.next
      - ./package.json:/app/package.json
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
