name: Build Deposit UI Docker image

on:
  push:
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - name: Checkout rome-deposit-ui repository
        uses: actions/checkout@v4
        with:
          repository: rome-labs/rome-deposit-ui
          path: rome-deposit-ui
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push amd64 image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: rome-deposit-ui
          file: rome-deposit-ui/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: romelabs/rome-deposit-ui:${{ github.ref_name }}

  build-arm64:
    runs-on: ubuntu-24.04-arm
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - name: Checkout rome-deposit-ui repository
        uses: actions/checkout@v4
        with:
          repository: rome-labs/rome-deposit-ui
          path: rome-deposit-ui
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GIT_ROLLUP_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push arm64 image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: rome-deposit-ui
          file: rome-deposit-ui/Dockerfile
          platforms: linux/arm64
          push: true
          provenance: false
          tags: romelabs/rome-deposit-ui:${{ github.ref_name }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create romelabs/rome-deposit-ui:${{ github.ref_name }} \
            --amend romelabs/rome-deposit-ui@${{ needs.build-amd64.outputs.digest }} \
            --amend romelabs/rome-deposit-ui@${{ needs.build-arm64.outputs.digest }}

          docker manifest push romelabs/rome-deposit-ui:${{ github.ref_name }}

      - name: Tag and push :latest (if on main)
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker manifest create romelabs/rome-deposit-ui:latest \
            --amend romelabs/rome-deposit-ui@${{ needs.build-amd64.outputs.digest }} \
            --amend romelabs/rome-deposit-ui@${{ needs.build-arm64.outputs.digest }}

          docker manifest push romelabs/rome-deposit-ui:latest
